# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edb23f126da5ba3934dc6677ec245a8b6c982c0ca097eacc4136300a76aecd47eab883d67d39d7baa355b4d31b047164ead30196860d5e60d9477ce0152cfa93

test:
  secret_key_base: c8d6b977adb8fdece19e34a0a683dbc0ad392f7a29ca6861d3543c7d42c6fe8a86678c933a094d053a886ca3b1d79707e80b491a23aafdced3470bd3c9f8b974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
